---@meta modules/mygame
--- @module "modules.MyGame.cells.floor"
prism.cells.Floor = nil
--- @module "modules.MyGame.cells.pit"
prism.cells.Pit = nil
--- @module "modules.MyGame.cells.wall"
prism.cells.Wall = nil
--- @module "modules.MyGame.actions.kick"
prism.actions.Kick = nil
--- @module "modules.MyGame.actions.move"
prism.actions.Move = nil
--- @module "modules.MyGame.actions.wait"
prism.actions.Wait = nil
--- @module "modules.MyGame.components.koboldcontroller"
prism.components.KoboldController = nil
--- @module "modules.MyGame.components.mover"
prism.components.Mover = nil
--- @module "modules.MyGame.actors.kobold"
prism.actors.Kobold = nil
--- @module "modules.MyGame.actors.player"
prism.actors.Player = nil